[package]
name = "benri"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.157", features = ["derive"]}
directories = "4.0.1"
serde_json = "1.0.94"
pyo3 = "0.18.1"
